---
title: Sprint!
hero_image: images/banner.png
description: Gebruik de pijltjestoetsen om zo snel mogelijk naar de finish te komen.
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
- title: Inleiding
  completion: engaged
- title: Op uw plaatsen...
- title: De afstand afleggen
- title: Wie is de snelste?
  completion: internal
- title: Landschap toevoegen
- title: 'Uitdaging: voeg een toeschouwer toe'
  challenge: true
- title: Wat kun je verder nog doen?
