---
title: स्प्रिंट!
hero_image: images/banner.png
description: जितनी जल्दी हो सके फिनिश लाइन पर पहुंचने के लिए एरो बटन का उपयोग करें।
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
  - title: परिचय
  - title: तुम्हारे प्राप्तांक पर (on your marks)...
  - title: दूरी तक जाना
  - title: सबसे तेज कौन है?
  - title: दृश्य जोड़ना
  - title: 'चुनौती: एक दर्शक जोड़ें'
    challenge: true
  - title: 'आगे क्या है?'
