---
title: 100メートル走
hero_image: images/banner.png
description: 矢印 (やじるし) キーを使って、できるだけ早くゴールまで走りましょう。
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
- title: はじめに
  completion: engaged
- title: 位置 (いち) について...
- title: ゴールまで走る
- title: 一番速いのはだれですか？
  completion: internal
- title: 風景 (ふうけい) を追加する
- title: 'チャレンジ: 観客 (かんきゃく) を追加する'
  challenge: true
- title: 次は何をしましょうか？
