---
title: Corrida!
hero_image: images/banner.png
description: Use as setas do teclado para alcançar à linha de chegada o mais rápido
  possível.
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
- title: Introdução
  completion: engaged
- title: Em suas marcas...
- title: Percorrendo a distância
- title: Quem é o mais rápido?
  completion: internal
- title: Adicionando cenário
- title: 'Desafio: Adicione um espectador'
  challenge: true
- title: E agora?
