---
title: '¡Carrera!'
hero_image: images/banner.png
description: Usa las teclas de flecha para llegar a la línea de meta lo más rápido que puedas.
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
  - title: Introducción
  - title: En sus marcas...
  - title: Atravesando la distancia
  - title: '¿Quién es el más rápido?'
  - title: Añadiendo el paisaje
  - title: 'Desafío: Añadir un espectador'
    challenge: true
  - title: '¿Qué sigue?'
