---
title: Sprint !
hero_image: images/banner.png
description: Utiliser les touches fléchées pour arriver à la ligne d'arrivée le plus rapidement possible.
listed: true
ingredient: false
copyedit: true
version: 4
last_tested: 2019-04-01
steps:
  - 
    title: Introduction
  - 
    title: À vos marques...
  - 
    title: Parcourir la distance
  - 
    title: Qui est le plus rapide ?
  - 
    title: Ajouter des décors
  - 
    title: 'Défi : Ajouter un spectateur'
    challenge: true
  - 
    title: 'Et ensuite ?'
